### ISSUE TITLE
create project

### ISSUE THREAD

**Issue by m-tmatma** [tma-jekyll-test/tma-jekyll-test.github.io#1]
create project

https://github.com/envygeeks/jekyll-docker/blob/master/README.md

https://github.com/envygeeks/jekyll-docker/blob/b8d394ad2a6b13fbbce23b6eea94cd9902f492e8/repos/jekyll/Dockerfile#L184-L187

http://jekyllrb-ja.github.io/docs/

**Comment by m-tmatma** [comment]
```
 docker run --rm --volume="$PWD:/srv/jekyll" -it -p 4000:4000 jekyll/jekyll jekyll new  .


ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
Running bundle install in /srv/jekyll...
  Bundler: Fetching gem metadata from https://rubygems.org/..........
  Bundler: Resolving dependencies...
  Bundler: Using bundler 2.2.24
  Bundler: Using colorator 1.1.0
  Bundler: Using concurrent-ruby 1.1.9
  Bundler: Using eventmachine 1.2.7
  Bundler: Using forwardable-extended 2.6.0
  Bundler: Using rb-fsevent 0.11.0
  Bundler: Using liquid 4.0.3
  Bundler: Using mercenary 0.4.0
  Bundler: Using safe_yaml 1.0.5
  Bundler: Using public_suffix 4.0.6
  Bundler: Fetching rouge 3.27.0
  Bundler: Fetching rexml 3.2.5
  Bundler: Using pathutil 0.16.2
  Bundler: Fetching ffi 1.15.5
  Bundler: Fetching unicode-display_width 1.8.0
  Bundler: Fetching http_parser.rb 0.8.0
  Bundler: Fetching i18n 1.9.1
  Bundler: Using addressable 2.8.0Bundler::PermissionError: There was an error while trying to write to
  Bundler: `/usr/gem/cache/http_parser.rb-0.8.0.gem`. It is likely that you need to grant
  Bundler: write permissions for that path.
  Bundler: An error occurred while installing http_parser.rb (0.8.0), and Bundler cannot
  Bundler: continue.
  Bundler: Make sure that `gem install http_parser.rb -v '0.8.0' --source
  Bundler: 'https://rubygems.org/'` succeeds before bundling.
  Bundler:
  Bundler: In Gemfile:
  Bundler: minima was resolved to 2.5.1, which depends on
  Bundler: jekyll-feed was resolved to 0.16.0, which depends on
  Bundler: jekyll was resolved to 4.2.1, which depends on
  Bundler: em-websocket was resolved to 0.5.3, which depends on
  Bundler: http_parser.rb
  Bundler:
  Bundler:
  Bundler: Bundler::PermissionError: There was an error while trying to write to
  Bundler: `/usr/gem/cache/i18n-1.9.1.gem`. It is likely that you need to grant write
  Bundler: permissions for that path.
  Bundler: An error occurred while installing i18n (1.9.1), and Bundler cannot continue.
  Bundler: Make sure that `gem install i18n -v '1.9.1' --source 'https://rubygems.org/'`
  Bundler: succeeds before bundling.
  Bundler:
  Bundler: In Gemfile:
  Bundler: minima was resolved to 2.5.1, which depends on
  Bundler: jekyll-feed was resolved to 0.16.0, which depends on
  Bundler: jekyll was resolved to 4.2.1, which depends on
  Bundler: i18n
  Bundler:
  Bundler:
  Bundler: Bundler::PermissionError: There was an error while trying to write to
  Bundler: `/usr/gem/cache/rexml-3.2.5.gem`. It is likely that you need to grant write
  Bundler: permissions for that path.
  Bundler: An error occurred while installing rexml (3.2.5), and Bundler cannot continue.
  Bundler: Make sure that `gem install rexml -v '3.2.5' --source 'https://rubygems.org/'`
  Bundler: succeeds before bundling.
  Bundler:
  Bundler: In Gemfile:
  Bundler: minima was resolved to 2.5.1, which depends on
  Bundler: jekyll-feed was resolved to 0.16.0, which depends on
  Bundler: jekyll was resolved to 4.2.1, which depends on
  Bundler: kramdown-parser-gfm was resolved to 1.1.0, which depends on
  Bundler: kramdown was resolved to 2.3.1, which depends on
  Bundler: rexml
  Bundler:
  Bundler:
  Bundler: Bundler::PermissionError: There was an error while trying to write to
  Bundler: `/usr/gem/cache/unicode-display_width-1.8.0.gem`. It is likely that you need to
  Bundler: grant write permissions for that path.
  Bundler: An error occurred while installing unicode-display_width (1.8.0), and Bundler
  Bundler: cannot continue.
  Bundler: Make sure that `gem install unicode-display_width -v '1.8.0' --source
  Bundler: 'https://rubygems.org/'` succeeds before bundling.
  Bundler:
  Bundler: In Gemfile:
  Bundler: minima was resolved to 2.5.1, which depends on
  Bundler: jekyll-feed was resolved to 0.16.0, which depends on
  Bundler: jekyll was resolved to 4.2.1, which depends on
  Bundler: terminal-table was resolved to 2.0.0, which depends on
  Bundler: unicode-display_width

```
